export type Category = 'Todos' | 'Mármol' | 'Granito' | 'Neolith' | 'Purastone' | 'Silestone' | 'Dekton' | 'Bachas' | 'Accesorios'

export interface Product {
  id: number
  name: string
  category: Category
  image: string
}

export const products: Product[] = [
  { id: 1, name: 'Milar', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752076/dekton-industrial-milar.jpg_wyh2jy.jpg' },
  { id: 2, name: 'Bromo', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752076/dekton-marmolesdestefano-natural-bromo.jpg_fziyum.jpg' },
  { id: 3, name: 'Lunar', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752076/dekton-industrial-lunar.jpg-1_wodwjc.jpg' },
  { id: 4, name: 'Radium', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752076/dekton-industrial-lunar.jpg-1_wodwjc.jpg' },
  { id: 5, name: 'Kreta', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752076/dekton-industrial-kreta.jpg_pasamj.jpg' },
  { id: 6, name: 'Soke', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752076/dekton-industrial-soke.jpg_tggop2.jpg' },
  { id: 7, name: 'Danae', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752076/dekton-marmolesdestefano-natural-danae.jpg_u2ot8t.jpg' },
  { id: 8, name: 'Nilium', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752076/dekton-industrial-nilium.jpg_jufaub.jpg' },
  { id: 9, name: 'Aura', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752077/dekton-marmolesdestefano-natural-aura15.jpg_ycz5sh.jpg' },
  { id: 10, name: 'Edora', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752077/dekton-marmolesdestefano-natural-edora.jpg_eah6ru.jpg' },
  { id: 11, name: 'Trilium', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752077/dekton-industrial-trilium.jpg_aaiw7h.jpg' },
  { id: 12, name: 'Fossil', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752077/dekton-marmolesdestefano-natural-fossil.jpg_eqcriu.jpg' },
  { id: 13, name: 'Entzo', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752077/dekton-marmolesdestefano-natural-entzo.jpg_dxmqhj.jpg' },
  { id: 14, name: 'Kairos', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752077/dekton-marmolesdestefano-natural-kairos.jpg_fbvxth.jpg' },
  { id: 15, name: 'Gada', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752077/dekton-marmolesdestefano-natural-gada.jpg_vnltmi.jpg' },
  { id: 16, name: 'Kelya', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752077/dekton-marmolesdestefano-natural-kelya.jpg_g4uuml.jpg' },
  { id: 17 , name: 'Kira', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752077/dekton-marmolesdestefano-natural-kira.jpg_naykze.jpg' },
  { id: 18, name: 'Kovik', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752077/dekton-marmolesdestefano-natural-kovik.jpg_wrnl8h.jpg' },
  { id: 19, name: 'Nayla', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752077/dekton-marmolesdestefano-natural-nayla.jpg_m5ziwp.jpg' },
  { id: 20, name: 'Opera', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752078/dekton-marmolesdestefano-natural-opera.jpg_hcmtj6.jpg' },
  { id: 21, name: 'Sasea', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752078/dekton-marmolesdestefano-natural-sasea.jpg_q6hlmq.jpg' },
  { id: 22, name: 'Vera', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752078/dekton-marmolesdestefano-natural-vera.jpg_erb4ru.jpg' },
  { id: 23, name: 'Vegha', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752078/dekton-marmolesdestefano-natural-vegha.jpg_bucdtm.jpg' },
  { id: 24, name: 'Sirocco', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752078/dekton-marmolesdestefano-natural-sirocco.jpg_hbqwcd.jpg' },
  { id: 25, name: 'Domoos', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752078/dekton-marmolesdestefano-solid-domoos.jpg_owke3z.jpg' },
  { id: 26, name: 'Korus', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752078/dekton-marmolesdestefano-solid-korus.jpg_ah39kc.jpg' },
  { id: 27 , name: 'Sirius', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752078/dekton-marmolesdestefano-solid-sirius.jpg_ycvowl.jpg' },
  { id: 28, name: 'Galema', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752078/dekton-marmolesdestefano-solid-galema.jpg_nnoczo.jpg' },
  { id: 29, name: 'Ventus', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752078/dekton-marmolesdestefano-solid-ventus.jpg_xqq51a.jpg' },
  { id: 30, name: 'Zenith', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752078/dekton-marmolesdestefano-solid-zenith.jpg_kvy8lq.jpg' },
  { id: 31, name: 'Bergen', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752079/dekton-marmolesdestefano-stonika-bergen.jpg_c8l497.jpg' },
  { id: 32, name: 'Arga', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752079/dekton-marmolesdestefano-stonika-arga.jpg_gmzzy6.jpg' },
  { id: 33, name: 'Korso', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752079/dekton-marmolesdestefano-stonika-korso.jpg-400x284_ny0a0o.jpg' },
  { id: 34, name: 'Sogne', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752079/dekton-marmolesdestefano-stonika-sogne.jpg_mo397y.jpg' },
  { id: 35, name: 'Olimpo', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752079/dekton-marmolesdestefano-stonika-olimpo.jpg_xgfyph.jpg' },
  { id: 36, name: 'Taga', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752079/dekton-marmolesdestefano-stonika-taga.jpg_dxaxxt.jpg' },
  { id: 37 , name: 'Concrete', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752079/dekton-marmolesdestefano-tech-blanc-concrete.jpg_fle4g1.jpg' },
  { id: 38, name: 'Keranium', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752079/dekton-marmolesdestefano-tech-keranium.jpg_igbdkv.jpg' },
  { id: 39, name: 'Keon', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752079/dekton-marmolesdestefano-tech-keon.jpg_j6r1gj.jpg' },
  { id: 40, name: 'Strato', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752079/dekton-marmolesdestefano-tech-strato.jpg_rwkasa.jpg' },
  { id: 41, name: 'Aldem', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752080/dekton-marmolesdestefano-wild-aldem.jpg_dsrkpw.jpg' },
  { id: 42, name: 'Makai', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752080/dekton-marmolesdestefano-wild-makai.jpg_zpcpae.jpg' },
  { id: 43, name: 'Manhattan', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752080/dekton-marmolesdestefano-xgloss-basiq-manhattan.jpg_hlofie.jpg' },
  { id: 44, name: 'Viena', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752080/dekton-marmolesdestefano-xgloss-basiq-viena.jpg_ektvp6.jpg' },
  { id: 45, name: 'Qatar', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752080/dekton-marmolesdestefano-xgloss-basiq-qatar.jpg_k8fn0m.jpg' },
  { id: 46, name: 'Glacier', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752080/dekton-marmolesdestefano-xgloss-natural.glacier.jpg_xhxzfv.jpg' },
  { id: 47 , name: 'Fiord', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752080/dekton-marmolesdestefano-xgloss-natural-fiord.jpg_uejzqx.jpg' },
  { id: 48, name: 'Halo', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752080/dekton-marmolesdestefano-xgloss-solid-halo.jpg_kqatjb.jpg' },
  { id: 49, name: 'Natura', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752080/dekton-marmolesdestefano-xgloss-natural-natura18.jpg_vewblw.jpg' },
  { id: 50, name: 'Blaze', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752080/dekton-marmolesdestefano-xgloss-solid-blaze.jpg_rjo3bt.jpg' },
  { id: 51, name: 'Tundra', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752080/dekton-marmolesdestefano-xgloss-natural-tundra.jpg_mrejvd.jpg' },
  { id: 52, name: 'Spectra', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752081/dekton-marmolesdestefano-xgloss-solid-spectra.jpg_frpme1.jpg' },
  { id: 53, name: 'Lumina', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752081/dekton-marmolesdestefano-xgloss-solid-lumina.jpg_xtlmoh.jpg' },
  { id: 54, name: 'Splendor', category: 'Dekton', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727752081/dekton-marmolesdestefano-xgloss-solid-splendor.jpg_cr3ks5.jpg' },
  
  { id: 55, name: 'Amarelo Ornamental', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757357/granito-marmolesdestefano-amarelo-ornamental.jpg_cpoup6.jpg' },
  { id: 56, name: 'Balmoral', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757358/granito-marmolesdestefano-balmoral.jpg_o8is67.jpg' },
  { id: 57, name: 'Beige Puma', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757360/granito-marmolesdestefano-beige_puma.jpg_tlhja9.jpg' },
  { id: 58, name: 'Beige Antico', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757360/granito-marmolesdestefano-beige_antico.jpg_tucrtt.jpg' },
  { id: 59, name: 'Bianco Antico', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757361/granito-marmolesdestefano-bianco_antico.jpg_datdyz.jpg' },
  { id: 60, name: 'Black Cosmic', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757362/granito-marmolesdestefano-black_cosmic.jpg_vr2uyb.jpg' },
  { id: 61, name: 'Blanco Dallas', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757362/granito-marmolesdestefano-blanco_dallas.jpg_pc1tsn.jpg' },
  { id: 62, name: 'Blanco Paris', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757363/granito-marmolesdestefano-blanco_paris.jpg_kfuypj.jpg' },
  { id: 63, name: 'Brown Antique', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757364/granito-marmolesdestefano-brown_antique.jpg_rwzsxf.jpg' },
  { id: 64, name: 'Cinza Grey', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757641/granito-marmolesdestefano-cinza_grey.jpg_biau2d.jpg' },
  { id: 65, name: 'Coffee Brown', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757687/granito-marmolesdestefano-coffee_brown.jpg_umcj3b.jpg' },
  { id: 66, name: 'Crema Colonial', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757744/granito-marmolesdestefano-crema_colonial.jpg_wiotgn.jpg' },
  { id: 67, name: 'Crema Julia', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757745/granito-marmolesdestefano-crema_julia.jpg_t5ina7.jpg' },
  { id: 68, name: 'Delicatus', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757746/granito-marmolesdestefano-delicatus.jpg_dztyz9.jpg' },
  { id: 69, name: 'Ebony Cristal', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757747/granito-marmolesdestefano-ebony_cristal.jpg_ugtj3a.jpg' },
  { id: 70, name: 'Galaxy Black', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757749/granito-marmolesdestefano-galaxy_black.jpg_pytzg5.jpg' },
  { id: 71, name: 'Gris Mara', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757749/granito-marmolesdestefano-gris_mara.jpg_xter3r.jpg' },
  { id: 72, name: 'Gris Perla', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757750/granito-marmolesdestefano-gris_perla.jpg_i4i6vz.jpg' },
  { id: 73, name: 'Gris Perla Salmon', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757752/granito-marmolesdestefano-gris_perla_salmon.jpg_ayh6fy.jpg' },
  { id: 74, name: 'Gris Plata', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757754/granito-marmolesdestefano-gris_plata.jpg_of3fdq.jpg' },
  { id: 75, name: 'Juparana Bordeaux', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757755/granito-marmolesdestefano-juparana_bordeaux.jpg_zprx0x.jpg' },
  { id: 76, name: 'Kashmire White', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757755/granito-marmolesdestefano-kashmire-white.jpg_ydh65f.jpg' },
  { id: 77, name: 'Lundhs Antique', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757757/granito-marmolesdestefano-lundhs_antique.jpg_izsexj.jpg' },
  { id: 78, name: 'Lundhs Blue', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757757/granito-marmolesdestefano-lundhs_blue.jpg_d4g2a3.jpg' },
  { id: 79, name: 'Marron Chino', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757758/granito-marmolesdestefano-marron_chino.jpg_l1nzr8.jpg' },
  { id: 80, name: 'Marron Coco', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757761/granito-marmolesdestefano-marron_coco.jpg_gjq30h.jpg' },
  { id: 81, name: 'Marron Grafito', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757763/granito-marmolesdestefano-marron_grafito.jpg_xos8zy.jpg' },
  { id: 82, name: 'Marron Sierra Chica Santa Fe', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757765/granito-marmolesdestefano-marron_sierra_chica_santafe.jpg_wbttdn.jpg' },
  { id: 83, name: 'Negro Absoluto Imperial', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757767/granito-marmolesdestefano-negro_absoluto_imperial.jpg_mczqdd.jpg' },
  { id: 84, name: 'Negro Boreal', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757770/granito-marmolesdestefano-negro_boreal.jpg_qowzyg.jpg' },
  { id: 85, name: 'Negro Brasil', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757772/granito-marmolesdestefano-negro_brasil.jpg_v8cnph.jpg' },
  { id: 86, name: 'Negro Indio Absoluto', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757774/granito-marmolesdestefano-negro_indio_absoluto.jpg_tmc1ct.jpg' },
  { id: 87, name: 'Negro Uruguayo', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757777/granito-marmolesdestefano-negro_uruguayo.jpg_w5s8o3.jpg' },
  { id: 88, name: 'Nero Marinace', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757779/granito-marmolesdestefano-nero-marinace.jpg_alw7fh.jpg' },
  { id: 89, name: 'New Venetian Gold', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757781/granito-marmolesdestefano-new-venetian-gold.jpg_hp2k4b.jpg' },
  { id: 90, name: 'Porfido Crema Cafe', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757784/granito-marmolesdestefano-porfido_crema_cafe.jpg_sxxedi.jpg' },
  { id: 91, name: 'Porfido Gris', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757786/granito-marmolesdestefano-porfido_gris.jpg_pmqdf6.jpg' },
  { id: 92, name: 'Rojo Dragon', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757788/granito-marmolesdestefano-rojo_dragon.jpg_ivg6ii.jpg' },
  { id: 93, name: 'Rojo Principe', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757791/granito-marmolesdestefano-rojo_principe.jpg_sf3akf.jpg' },
  { id: 94, name: 'Rojo Sierra Chica', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757793/granito-marmolesdestefano-rojo_sierra_chica.jpg_vcvtkj.jpg' },
  { id: 95, name: 'Rosa Coco', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757795/granito-marmolesdestefano-rosa_coco.jpg_z0lpff.jpg' },
  { id: 96, name: 'Rosa del Salto', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757798/granito-marmolesdestefano-rosa_del_salto.jpg_h7dq52.jpg' },
  { id: 97, name: 'Rosa Mara Super', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757800/granito-marmolesdestefano-rosa_mara_super.jpg_vmifdb.jpg' },
  { id: 98, name: 'Rosa Siena', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757802/granito-marmolesdestefano-rosa_siena.jpg_yshujr.jpg' },
  { id: 99, name: 'Rumi Black', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757804/granito-marmolesdestefano-rumi_black.jpg_maqass.jpg' },
  { id: 89, name: 'San Felipe', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757807/granito-marmolesdestefano-san_felipe.jpg_ejlg6y.jpg' },
  { id: 89, name: 'Santa Cecilia', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757809/granito-marmolesdestefano-santa_cecilia.jpg_ty8p65.jpg' },
  { id: 89, name: 'Sierra Lilaceo', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757811/granito-marmolesdestefano-sierra_lilaceo.jpg_n6uzav.jpg' },
  { id: 89, name: 'Titanium', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757814/granito-marmolesdestefano-titanium.jpg_lgtseu.jpg' },
  { id: 89, name: 'Verde Butterfly', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757816/granito-marmolesdestefano-verde_butterfly.jpg_n4bnc3.jpg' },
  { id: 89, name: 'Verde Marinace', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757818/granito-marmolesdestefano-verde_marinace.jpg_uswypi.jpg' },
  { id: 89, name: 'Verde San Francisco', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757820/granito-marmolesdestefano-verde_san_francisco.jpg_xt5uyw.jpg' },
  { id: 89, name: 'Verde Ubatuba', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757823/granito-marmolesdestefano-verde_ubatuba.jpg-1_ied2q1.jpg' },
  { id: 90, name: 'Volga Blue', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757825/granito-marmolesdestefano-volga_blue.jpg_tauo1g.jpg' },
  { id: 91, name: 'White Pearl', category: 'Granito', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727757827/granito-marmolesdestefano-white_pearl.jpg-1_uufzyo.jpg' },

  { id: 92, name: 'Arabescato Vagli', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727759996/marmol-marmolesdestefano-arabescato_vagli.jpg_xpkwbz.jpg' },
  { id: 93, name: 'Antracite Dark', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727759996/marmol-marmolesdestefano-antracite_dark.jpg_lzqnqu.jpg' },
  { id: 94, name: 'Verde Ubatuba', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727759996/granito-marmolesdestefano-verde_ubatuba.jpg_kyhgez.jpg' },
  { id: 95, name: 'Dardiglio', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727759996/marmol-marmolesdestefano-bardiglio.jpg_a8axxv.jpg' },
  { id: 96, name: 'Arabescato Cervaiole', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727759996/marmol-marmolesdestefano-arabescato_cervaiole.jpg_f7fjdr.jpg' },
  { id: 97, name: 'Beige Sahara', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727759996/marmol-marmolesdestefano-beige_sahara.jpg_juizkj.jpg' },
  { id: 98, name: 'Blanco Botticino', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727759996/marmol-marmolesdestefano-blanco_botticino.jpg_bhpelf.jpg' },
  { id: 99, name: 'Blanco Carrara', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727759996/marmol-marmolesdestefano-blanco_carrara.jpg_wwlo2z.jpg' },
  { id: 100, name: 'Blanco Griego Dolomita Areti', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727759997/marmol-marmolesdestefano-blanco_griego_dolomita_areti.jpg_zhl0ym.jpg' },
  { id: 101, name: 'Blanco Macael', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727759999/marmol-marmolesdestefano-blanco_macael.jpg_tzapxy.jpg' },
  { id: 102, name: 'Blanco Pentelico', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727759999/marmol-marmolesdestefano-blanco_pentelico.jpg_ui3nnt.jpg' },
  { id: 103, name: 'Blanco Royal', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727759999/marmol-marmolesdestefano-blanco_royal.jpg_hsmuzy.jpg' },
  { id: 104, name: 'Blanco Perlino', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727759999/marmol-marmolesdestefano-blanco_perlino.jpg_txsxyi.jpg' },
  { id: 105, name: 'Blanco Sivec', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727759999/marmol-marmolesdestefano-blanco_sivec.jpg_x7yh6j.jpg' },
  { id: 106, name: 'Calacatta', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727759999/marmol-marmolesdestefano-calacatta.jpg_ngnz2p.jpg' },
  { id: 107, name: 'Calacatta Vagli Oro', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727759999/marmol-marmolesdestefano-calacatta_vagli_oro.jpg_xfhllm.jpg' },
  { id: 108, name: 'Crema Marfil', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727759999/marmol-marmolesdestefano-crema_marfil.jpg_kuvo41.jpg' },
  { id: 109, name: 'Crema Valencia', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727759999/marmol-marmolesdestefano-crema_valencia.jpg_zvcbnf.jpg' },
  { id: 110, name: 'Desert Brown', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760000/marmol-marmolesdestefano-desert_brown.jpg_mcrgnf.jpg' },
  { id: 111, name: 'Dessert Cream', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760001/marmol-marmolesdestefano-dessert_cream.jpg_qbygwk.jpg' },
  { id: 122, name: 'Estatuarieto', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760002/marmol-marmolesdestefano-estatuarieto.jpg_hr81fj.jpg' },
  { id: 123, name: 'Estatuario', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760002/marmol-marmolesdestefano-estatuario.jpg_jcjl25.jpg' },
  { id: 124, name: 'Goflan Silver', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760002/marmol-marmolesdestefano-goflan_silver.jpg_jnpiuf.jpg' },
  { id: 125, name: 'Grigio Nuvola', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760002/marmol-marmolesdestefano-grigio_nuvola.jpg_vk4fkl.jpg' },
  { id: 126, name: 'Fior di Pesco', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760002/marmol-marmolesdestefano-fior_di_pesco.jpg_g5ahkk.jpg' },
  { id: 127, name: 'Imperial Beige', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760002/marmol-marmolesdestefano-imperial_beige.jpg_f2le2n.jpg' },
  { id: 128, name: 'Marron Bosque Gold', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760002/marmol-marmolesdestefano-marron_bosque_gold.jpg_somgax.jpg' },
  { id: 130, name: 'Marron Imperial', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760002/marmol-marmolesdestefano-marron_imperial.jpg_du1zpr.jpg' },
  { id: 131, name: 'Negro Marquina', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760002/marmol-marmolesdestefano-negro_marquina.jpg_wfnmru.jpg' },
  { id: 132, name: 'Perlado', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760004/marmol-marmolesdestefano-perlado.jpg_gcnugp.jpg' },
  { id: 133, name: 'Rojo Alicante', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760004/marmol-marmolesdestefano-rojo_alicante_extra.jpg_ksahoq.jpg' },
  { id: 134, name: 'Rosalia', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760004/marmol-marmolesdestefano-rosalia.jpg_raszxl.jpg' },
  { id: 135, name: 'Silver Wave', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760005/marmol-marmolesdestefano-silver_wave.jpg_kvebhh.jpg' },
  { id: 136, name: 'Rosso Verona', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760005/marmol-marmolesdestefano-rosso_verona.jpg_plzgah.jpg' },
  { id: 137, name: 'Verde Bosque', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760005/marmol-marmolesdestefano-verde_bosque.jpg_vjdhzd.jpg' },
  { id: 138, name: 'Portoro', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760004/marmol-marmolesdestefano-portoro.jpg_decouw.jpg' },
  { id: 139, name: 'Verde Remiggiato', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760005/marmol-marmolesdestefano-verde_remiggiato.jpg_faz76e.jpg' },
  { id: 140, name: 'Verde Oriental', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760005/marmol-marmolesdestefano-verde_oriental.jpg_sczfby.jpg' },
  { id: 141, name: 'Verde Tinos', category: 'Mármol', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727760005/marmol-marmolesdestefano-verde_tinos.jpg_uhjjrt.jpg' },

  { id: 142, name: 'Calacatta Gold', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798259/neolith-marmolesdestefano-classtone-calacatta-gold-cg01.jpg_d20ink.jpg' },
  { id: 143, name: 'Calacatta', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798259/neolith-marmolesdestefano-classtone-calacatta-c01.jpg_x2zqn0.jpg' },
  { id: 144, name: 'Calatorao', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798259/neolith-marmolesdestefano-classtone-calatorao.jpg_epu0kj.jpg' },
  { id: 145, name: 'Estatuario', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798302/neolith-marmolesdestefano-classtone-estatuario-e05r.jpg_sse1ou.jpg' },
  { id: 146, name: 'Mont Blanc', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798507/neolith-marmolesdestefano-classtone-neolith-mont-blanc.jpg_k1bhem.jpg' },
  { id: 147, name: 'Pulpis', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798507/neolith-marmolesdestefano-classtone-pulpis.jpg_vffhvr.jpg' },
  { id: 148, name: 'Strata Argentum', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798508/neolith-marmolesdestefano-classtone-strata-argentum.jpg_hi4rki.jpg' },
  { id: 149, name: 'Arctic White', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798509/neolith-marmolesdestefano-colorfeel-arctic-white.jpg_jd3vca.jpg' },
  { id: 150, name: 'Bombon', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798510/neolith-marmolesdestefano-colorfeel-bombon.jpg_p9tal4.jpg' },
  { id: 151, name: 'Humo', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798510/neolith-marmolesdestefano-colorfeel-humo.jpg_j8fxkg.jpg' },
  { id: 152, name: 'Luna', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798511/neolith-marmolesdestefano-colorfeel-luna.jpg_oqaj2t.jpg' },
  { id: 153, name: 'Just White', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798511/neolith-marmolesdestefano-colorfeel-neolith-just-white.jpg_lvrbox.jpg' },
  { id: 154, name: 'Nero', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798512/neolith-marmolesdestefano-colorfeel-nero.jpg_w8oypu.jpg' },
  { id: 155, name: 'Nieve', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798513/neolith-marmolesdestefano-colorfeel-nieve.jpg_yyysky.jpg' },
  { id: 156, name: 'Perla', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798514/neolith-marmolesdestefano-colorfeel-perla.jpg_bitsys.jpg' },
  { id: 157, name: 'Arena', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798514/neolith-marmolesdestefano-fusion-arena.jpg_dn6qnh.jpg' },
  { id: 158, name: 'Aspen Grey', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798515/neolith-marmolesdestefano-fusion-aspen-grey.jpg_fq7imp.jpg' },
  { id: 159, name: 'Barro', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798516/neolith-marmolesdestefano-fusion-barro.jpg_unod4i.jpg' },
  { id: 160, name: 'Basalt Beige', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798518/neolith-marmolesdestefano-fusion-basalt-beige.jpg_s5xpsm.jpg' },
  { id: 161, name: 'Basalt Grey', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798519/neolith-marmolesdestefano-fusion-basalt-grey.jpg_egqykf.jpg' },
  { id: 162, name: 'Basalt Black', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798518/neolith-marmolesdestefano-fusion-basalt-black-1024x246.jpg-400x284_vjiaox.jpg' },
  { id: 163, name: 'Beton', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798519/neolith-marmolesdestefano-fusion-beton.jpg_rhruqf.jpg' },
  { id: 164, name: 'Cement', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798520/neolith-marmolesdestefano-fusion-cement.jpg_ktb4zb.jpg' },
  { id: 165, name: 'Concrete Taupe', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798521/neolith-marmolesdestefano-fusion-concrete-taupe.jpg_begybv.jpg' },
  { id: 166, name: 'Krater', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798522/neolith-marmolesdestefano-fusion-krater.jpg_yj4bid.jpg' },
  { id: 167, name: 'Lava', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798522/neolith-marmolesdestefano-fusion-lava.jpg_z2cozg.jpg' },
  { id: 168, name: 'Mar del Plata', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798523/neolith-marmolesdestefano-fusion-mar-del-plata.jpg_vlt4xg.jpg' },
  { id: 169, name: 'Mirage', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798524/neolith-marmolesdestefano-fusion-mirage.jpg_ms8fym.jpg' },
  { id: 170, name: 'Nero Zimbabwe', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798525/neolith-marmolesdestefano-fusion-nero-zimbabwe.jpg_z3x9w8.jpg' },
  { id: 171, name: 'New York', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798525/neolith-marmolesdestefano-fusion-neolith-new-york-new-york.jpg_vjodjg.jpg' },
  { id: 172, name: 'Phedra', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798526/neolith-marmolesdestefano-fusion-phedra.jpg_rqam9w.jpg' },
  { id: 173, name: 'Pierre Bleue', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798526/neolith-marmolesdestefano-fusion-pierre-bleue.jpg_p6xmib.jpg' },
  { id: 174, name: 'Pietra di Luna', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798527/neolith-marmolesdestefano-fusion-pietra-di-luna.jpg_zmrxi3.jpg' },
  { id: 175, name: 'Pietra di Osso', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798528/neolith-marmolesdestefano-fusion-pietra-di-osso.jpg_v2koe1.jpg' },
  { id: 176, name: 'Retrostone', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798529/neolith-marmolesdestefano-fusion-retrostone.jpg_z9zbc2.jpg' },
  { id: 177, name: 'Zaha Stone', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798530/neolith-marmolesdestefano-fusion-zaha-stone.jpg_pfso96.jpg' },
  { id: 178, name: 'Pietra di Piombo', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798529/neolith-marmolesdestefano-fusion-pietra-di-piombo.jpg_wsmonk.jpg' },
  { id: 179, name: 'Iron Copper', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798530/neolith-marmolesdestefano-iron-copper.jpg_irasa8.jpg' },
  { id: 180, name: 'Iron Corten', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798531/neolith-marmolesdestefano-iron-corten.jpg_fmuged.jpg' },
  { id: 181, name: 'Iron Frost', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798533/neolith-marmolesdestefano-iron-frost.jpg_wycycg.jpg' },
  { id: 182, name: 'Iron Grey', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798533/neolith-marmolesdestefano-iron-grey.jpg_pk38rv.jpg' },
  { id: 183, name: 'Iron Moss', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798534/neolith-marmolesdestefano-iron-moss.jpg_shfnll.jpg' },
  { id: 184, name: 'Sofia Coprum', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798535/neolith-marmolesdestefano-steel-sofia-coprum.jpg_syxqsa.jpg' },
  { id: 185, name: 'Textil White', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798535/neolith-marmolesdestefano-textil-white.jpg_cm3soq.jpg' },
  { id: 186, name: 'Timber la Boheme', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798536/neolith-marmolesdestefano-timber-la-boheme.jpg_af5efl.jpg' },
  { id: 187, name: 'Blanco Carrara', category: 'Neolith', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727798536/WhatsApp_Image_2024-03-20_at_23.50.53_uuxoao.jpg' },
 
  { id: 188, name: 'Arabescato Cervaiole', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801316/Arabescato-Cervaiole-1_a63rvr.jpg' },
  { id: 189, name: 'Arabescato Venatino', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801317/Arabescato-Venatino_kqcydj.jpg' },
  { id: 190, name: 'Basaltina', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801318/Basaltina.jpg_fgfryp.jpg' },
  { id: 191, name: 'Bianco Luxe', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801595/Bianco-Luxe.jpg_mllsc5.jpg' },
  { id: 192, name: 'Bianco Silver', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801595/Bianco-Silver.jpg_ikjyat.jpg' },
  { id: 193, name: 'Blanco Cana', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801597/Blanco-Cana.jpg_cebysc.jpg' },
  { id: 194, name: 'Blanco Glitter', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801598/Blanco-Glitter-1.jpg_jdjbtr.jpg' },
  { id: 195, name: 'Blanco Icon', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801599/Blanco-Icon-1.jpg_l0kcxc.jpg' },
  { id: 196, name: 'Blanco Nube', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801601/Blanco-Nube-1.jpg_eclhj2.jpg' },
  { id: 197, name: 'Blanco Paloma', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801601/Blanco-Paloma.jpg_flcwlp.jpg' },
  { id: 198, name: 'Calacatta Antico', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801604/Calacatta-Antico_digyg8.jpg' },
  { id: 199, name: 'Calacatta Borghini', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801604/Calacatta-Borghini_dvjkra.jpg' },
  { id: 200, name: 'Cemento', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801605/Cemento.jpg_bg3mzi.jpg' },
  { id: 201, name: 'Calacatta Clasico', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801605/Calacatta-Clasico_ogthqz.jpg' },
  { id: 202, name: 'Crema Prisa', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801699/Crema-Prisa.jpg_giwxn9.jpg' },
  { id: 203, name: 'Estatuario Venato', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801701/Estatuario-Venato_twhada.jpg' },
  { id: 204, name: 'Greyge', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801701/Greyge.jpg_c1v6lw.jpg' },
  { id: 205, name: 'Gris Fosil', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801703/Gris-Fosil.jpg_gwhkht.jpg' },
  { id: 206, name: 'Gris Topo', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801851/Gris-Topo.jpg_zsheyq.jpg' },
  { id: 207, name: 'Gris Zen', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727801852/Gris-Zen.jpg_slddf7.jpg' },
  { id: 208, name: 'Negro Glitter', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802003/Negro_Glitter_PC3P05P20J_PR.jpg_fnalm2.jpg' },
  { id: 209, name: 'Negro Betun', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802003/Negro-Betun.jpg_sky4s3.jpg' },
  { id: 210, name: 'Negro Marquina', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802004/Negro-Marquina.jpg_ay66zr.jpg' },
  { id: 211, name: 'Noir', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802004/Noir.jpg_qnobkb.jpg' },
  { id: 212, name: 'Concrete', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802005/Pura-Concrete.jpg_oc0rfp.jpg' },
  { id: 213, name: 'Concrete Dark', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802006/Pura-Concrete-Dark.jpg_jsm6o8.jpg' },
  { id: 214, name: 'Statuarietto', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802007/Pura-Statuarietto.jpg_w6fmsa.jpg' },
  { id: 215, name: 'Statuario', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802008/Statuario.jpg_ami14j.jpg' },
  { id: 216, name: 'Invisible Grey', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802011/Invisible-Grey_gemfvl.jpg' },
  { id: 217, name: 'Terrazo White', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802056/Terrazo-White.jpg_ke9nrt.jpg' },
  { id: 218, name: 'Venatino', category: 'Purastone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802056/Venatino.jpg_idfanl.jpg' },

  { id: 219, name: 'Blanco Zeus', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802507/silestone-marmoles_destefano-blanco_zeus.jpg_kwfxjr.jpg' },
  { id: 220, name: 'Acqua Fraccaroli', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802507/silestone-marmolesdestefano-acqua-fraccaroli.jpg_nkuvpb.jpg' },
  { id: 221, name: 'Aluminio Nube', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802508/silestone-marmolesdestefano-aluminio_nube.jpg_j4utmg.jpg' },
  { id: 222, name: 'Blanco Capri', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802510/silestone-marmolesdestefano-blanco_capri.jpg_nr3ekx.jpg' },
  { id: 223, name: 'Blanco City', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802510/silestone-marmolesdestefano-blanco_city.jpg_rqzvv1.jpg' },
  { id: 224, name: 'Blanco Dune', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802512/silestone-marmolesdestefano-blanco_dune.jpg_v5nt2s.jpg' },
  { id: 225, name: 'Blanco Maple', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802512/silestone-marmolesdestefano-blanco_maple.jpg_i6axan.jpg' },
  { id: 226, name: 'Blanco Norte', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802514/silestone-marmolesdestefano-blanco_norte.jpg_gl1yej.jpg' },
  { id: 227, name: 'Blanco Orion', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802514/silestone-marmolesdestefano-blanco_orion.jpg_v68udq.jpg' },
  { id: 228, name: 'Carbono', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802516/silestone-marmolesdestefano-carbono.jpg_wolyeu.jpg' },
  { id: 229, name: 'Cemento Spa', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802517/silestone-marmolesdestefano-cemento_spa.jpg_sjcnrv.jpg' },
  { id: 230, name: 'Chrome', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802518/silestone-marmolesdestefano-chrome.jpg_hm0hhm.jpg' },
  { id: 231, name: 'Crema Minerva', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802519/silestone-marmolesdestefano-crema_minerva.jpg_yxgecx.jpg' },
  { id: 232, name: 'Eco Polar', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802520/silestone-marmolesdestefano-eco_polar_cap.jpg_argzr9.jpg' },
  { id: 233, name: 'Eternal Calacatta', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802521/silestone-marmolesdestefano-eternal-calacatta_gold.jpg_xusnss.jpg' },
  { id: 234, name: 'Eternal Charcoal', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802522/silestone-marmolesdestefano-eternal-charcoal.jpg_jvifbo.jpg' },
  { id: 235, name: 'Eternal Marquina', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802523/silestone-marmolesdestefano-eternal-marquina.jpg_iadlxw.jpg' },
  { id: 236, name: 'Eternal Peal Jasmine', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802524/silestone-marmolesdestefano-eternal-pearl-jasmine.jpg_uvi0ft.jpg' },
  { id: 237, name: 'Eternal Serena', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802525/silestone-marmolesdestefano-eternal-serena.jpg_ivik4q.jpg' },
  { id: 238, name: 'Gedatsu', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802526/silestone-marmolesdestefano-gedatsu.jpg_bfkh5h.jpg' },
  { id: 239, name: 'Gris Expo', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802527/silestone-marmolesdestefano-gris_expo.jpg_mvpnby.jpg' },
  { id: 240, name: 'Lyra', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802529/silestone-marmolesdestefano-lyra.jpg_reo9kz.jpg' },
  { id: 241, name: 'Magenta Energy', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802529/silestone-marmolesdestefano-magenta_energy.jpg_t3xphs.jpg' },
  { id: 242, name: 'Marengo', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802531/silestone-marmolesdestefano-marengo.jpg_zc7sz2.jpg' },
  { id: 243, name: 'Mont Blanc', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802531/silestone-marmolesdestefano-mont_blanc.jpg_hjajil.jpg' },
  { id: 244, name: 'Naranja Cool', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802533/silestone-marmolesdestefano-naranja_cool.jpg_sm2dxp.jpg' },
  { id: 245, name: 'Negro Stellar', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802534/silestone-marmolesdestefano-negro_stellar.jpg_yft6mk.jpg' },
  { id: 246, name: 'Negro Tebas', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802535/silestone-marmolesdestefano-negro_tebas.jpg_j12uqv.jpg' },
  { id: 247, name: 'Niebla', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802536/silestone-marmolesdestefano-niebla.jpg_ny4zyd.jpg' },
  { id: 248, name: 'Noka', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802537/silestone-marmolesdestefano-noka.jpg_lrc7fe.jpg' },
  { id: 249, name: 'Pulsar', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802538/silestone-marmolesdestefano-pulsar.jpg_wvry0a.jpg' },
  { id: 250, name: 'Rojo Eros', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802539/silestone-marmolesdestefano-rojo_eros.jpg_pzexgo.jpg' },
  { id: 251, name: 'Rojo Eros Stellar', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802540/silestone-marmolesdestefano-rojo_eros_stellar.jpg_yrjejz.jpg' },
  { id: 252, name: 'Rosso Monza', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802541/silestone-marmolesdestefano-rosso_monza.jpg_gavxqf.jpg' },
  { id: 253, name: 'Ruogui', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802542/silestone-marmolesdestefano-rougui.jpg_rjhoox.jpg' },
  { id: 254, name: 'Steel', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802543/silestone-marmolesdestefano-steel.jpg_t0ojsg.jpg' },
  { id: 255, name: 'Unsui', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802544/silestone-marmolesdestefano-unsui.jpg_txtfqj.jpg' },
  { id: 256, name: 'Verde Fun', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802546/silestone-marmolesdestefano-verde_fun.jpg_pwlgsq.jpg' },
  { id: 257, name: 'White Platinum', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802546/silestone-marmolesdestefano-white_platinum.jpg_lbwica.jpg' },
  { id: 258, name: 'White Storm', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802548/silestone-marmolesdestefano-white_storm.jpg_fu1vx6.jpg' },
  { id: 259, name: 'Yukon', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802548/silestone-marmolesdestefano-yukon.jpg_kewvse.jpg' },
  { id: 260, name: 'Zirconium', category: 'Silestone', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727802550/silestone-marmolesdestefano-zirconium.jpg_ojz9lx.jpg' },

  { id: 261, name: 'C28/18', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727805500/01.-C28-18-sin-accesorios_gxfit9.jpg' },
  { id: 262, name: 'C37', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727805500/01.-C37-sin-accesorios_wyxbtb.jpg' },
  { id: 263, name: 'E28', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727805502/01.-E28-sola_vpus50.jpg' },
  { id: 264, name: 'E37', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806029/01.-E37-sin-accesorios_u6hg4q.jpg' },
  { id: 265, name: 'E44', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806029/01.-E44-SIN-ACCESORIOS_h1b1hh.jpg' },
  { id: 266, name: 'E50/18', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806031/01.-E50-18-sola_kryb5l.jpg' },
  { id: 267, name: 'E54', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806032/01.-E54-sola_uuilnb.jpg' },
  { id: 268, name: 'G50', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806034/01.-G50-sola_uezptp.jpg' },
  { id: 269, name: 'Q55', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806035/01.-Q55_svn3uu.jpg' },
  { id: 270, name: 'R37', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806037/01.-R37-sola_ss1vaz.jpg' },
  { id: 271, name: 'R63', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806038/01.-R63-18F-Sin-Accesorio_q8hda1.jpg' },
  { id: 272, name: 'R63/18', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806040/01.-R63-18-Sin-Accesorios_b7pgg6.jpg' },
  { id: 273, name: 'X28', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806041/01.-X28-SOLA_rslqqq.jpg' },
  { id: 274, name: 'Z52/18', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806043/01.-Z52-18-Sin-Accesorio_enucuo.jpg' },
  { id: 275, name: 'Curve SI77 A', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806044/1_CURVE_jshe8g.jpg' },
  { id: 276, name: 'Luxor Mini SI55 A', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806046/1_LUXOR-SI55_tw0oie.jpg' },
  { id: 277, name: 'Luxor Compact SI71', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806047/1_LUXOR-SI71_wbivm7.jpg' },
  { id: 278, name: 'Luxor SI85', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806048/1_LUXOR-SI85_cuvz3h.jpg' },
  { id: 279, name: 'Zara D84 A', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806050/1_ZARA_D84A_kwpnkh.jpg' },
  { id: 280, name: 'ZN52/18', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806052/1_ZN52-18_-A_efoppl.jpg' },
  { id: 281, name: 'Axa D78 A', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806053/Axa_D78_A_k1vg6h.jpg' },
  { id: 282, name: 'E60', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806055/E60_v969ul.jpg' },
  { id: 283, name: 'Hydra J 107 A', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806056/Hydra_J_107_A_fu6ha6.jpg' },
  { id: 284, name: 'O37 A', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806058/O37_A_ncwawf.jpg' },
  { id: 285, name: 'ON 30A', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806059/ON-30A-e1422976534868_hueisq.jpg' },
  { id: 286, name: 'Q37', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806061/Q37_vh208n.jpg' },
  { id: 287, name: 'Q40', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806062/Q40_y47okg.jpg' },
  { id: 288, name: 'Q71', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806064/Q71_ktgbvl.jpg' },
  { id: 289, name: 'Q76', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806065/Q76_sjw3h0.jpg' },
  { id: 290, name: 'Q084 A', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806068/Q084_A_zt65wa.jpg' },
  { id: 291, name: 'Q085 A', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806070/Q085_A_lspxl3.jpg' },
  { id: 292, name: 'T34', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806071/T34_rkvql5.jpg' },
  { id: 293, name: 'G50', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727833889/pileta-lavadero-G50-sola_nvzlhf.jpg' },
  { id: 294, name: 'LN50', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727833888/01.-LN50-sola_fbkoma.jpg' },
  { id: 295, name: 'O 300L', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727833895/1-O-300-L-e1430739312274_xcbpiq.jpg' },
  { id: 296, name: 'O 250L', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727833896/2-O-250-L-e1430739336419_aofmai.jpg' },
  { id: 297, name: 'OV 330L', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727833896/3-OV-330L-e1430739533676_xlmykb.jpg' },
  { id: 298, name: 'OV 440L', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727833897/4-OV-440-L-e1430739463836_ivdmi0.jpg' },
  { id: 299, name: 'OV 370L', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727833898/5-OV-370L-e1430739556739_ighatr.jpg' },
  { id: 300, name: 'Baly 340L', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727833899/6-BALY-340L-e1430739379460_cwsrlg.jpg' },
  { id: 301, name: 'O 340L', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727833900/8-O-340L-e1430739354262_yxyoyd.jpg' },
  { id: 302, name: 'Danna', category: 'Bachas', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727833900/DANNA-0-1057x893_s1pjce.jpg' },

  { id: 303, name: 'Bandeja de acero inox. rejilla E44', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806085/Bandeja_de_acero_inox._rejilla_E44_uo0arj.jpg' },
  { id: 304, name: 'Canasto de acero inoxidable E37', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806087/Canasto_de_acero_inoxidable_E37_pyu937.jpg' },
  { id: 305, name: 'Canasto secaplatos Luxor de Acero Inoxidable', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806088/Canasto_secaplatos_Luxor_de_Acero_Inoxidable_ra6dbp.jpg' },
  { id: 306, name: 'Canasto secaplatos Luxor Mini de Acero Inoxidable', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806090/Canasto_secaplatos_Luxor_Mini_Acero_Inoxidable_pl3oqg.jpg' },
  { id: 307, name: 'Cubre cestillo', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806091/Cubre_cestillo_momsfx.jpg' },
  { id: 308, name: 'Dosificador Cubo', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806093/Dosificador_Cubo_zwwzsa.jpg' },
  { id: 309, name: 'Dosificador Apido', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806094/Dosificador_vd09m3.jpg' },
  { id: 310, name: 'Escurreplatos Curve Acero Inoxidable E37', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806096/Escurreplatos_Curve_Acero_Inoxidable_xott78.jpg' },
  { id: 311, name: 'Escurreplatos de acero Inox. E3', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806098/Escurreplatos_de_acero_Inox._E3_mnw0kg.jpg' },
  { id: 312, name: 'Escurreplatos de acero Inox. E4', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806099/Escurreplatos_de_acero_Inox._E4_sku7gg.jpg' },
  { id: 313, name: 'Escurreplatos de acero inox. Q37', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806101/Escurreplatos_de_acero_inox._Q37_bwq0lu.jpg' },
  { id: 314, name: 'Escurreplatos de acero inox. Q40', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806102/Escurreplatos_de_acero_inox._Q40_aqqdzc.jpg' },
  { id: 315, name: 'Escurreplatos de acero inox. Quadra Max Q71 A', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806104/Escurreplatos_de_acero_inox._Quadra_Max_Q71_A_iqmay4.jpg' },
  { id: 316, name: 'Kit grampas colocación pileta de abajo', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806105/Kit_grampas_colocaci%C3%B3n_pileta_de_abajo_n7ifn3.jpg' },
  { id: 317, name: 'Pileta accesoria Luxor en ABS color blanco con aro de apoyo de acero inoxidable', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806107/Pileta_accesoria_Luxor_en_ABS_color_blanco_con_aro_de_apoyo_de_acero_inoxidable_d2apv8.jpg' },
  { id: 318, name: 'Pileta accesoria Luxor en ABS color negro con aro de apoyo de acero inoxidable', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806108/Pileta_accesoria_Luxor_en_ABS_color_negro_con_aro_de_apoyo_de_acero_inoxidable_p8xfol.jpg' },
  { id: 319, name: 'Pileta accesoria Quadra Max Q71 A en ABS color blanco', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806110/Pileta_accesoria_Quadra_Max_Q71_A_en_ABS_color_blanco_dbym6r.jpg' },
  { id: 320, name: 'Pileta accesoria Quadra Max Q71 A en ABS color negro', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806111/Pileta_accesoria_Quadra_Max_Q71_A_en_ABS_color_negro_vwcalk.jpg' },
  { id: 321, name: 'Piletín ABS Blanco', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806113/Pilet%C3%ADn_ABS_blanco_uz9a7z.jpg' },
  { id: 322, name: 'Sopapa americana', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806114/Sopapa_americana_iaesdg.jpg' },
  { id: 323, name: 'Sopapa cestillo con brazo antirrebalse', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806116/Sopapa_cestillo_con_brazo_antirrebalse_ou7jsy.jpg' },
  { id: 324, name: 'Sopapa cestillo cuadrada con brazo antirrebalse', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806118/Sopapa_cestillo_cuadrada_con_brazo_antirrebalse_at1pwr.jpg' },
  { id: 325, name: 'Sopapa cestillo cuadrada', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806119/Sopapa_cestillo_cuadrada_t2pqtn.jpg' },
  { id: 326, name: 'Sopapa cestillo PR con brazo antirrebalse', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806121/Sopapa_cestillo_PR_con_brazo_antirrebalse_Cover_bmo5dh.jpg' },
  { id: 327, name: 'Sopapa Cestillo PR', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806122/Sopapa_Cestillo_PR_simrly.jpg' },
  { id: 328, name: 'Sopapa Cestillo', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806123/Sopapa_Cestillo_pwbmbj.jpg' },
  { id: 329, name: 'Sopapa Standard', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806125/Sopapa_standard_ex6cpg.jpg' },
  { id: 330, name: 'Suplemento Luxor Compact SI71 para grifería monocomando', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806127/Suplemento_Luxor_Compact_para_grifer%C3%ADa_monocomando_tzrgtr.jpg' },
  { id: 331, name: 'Suplemento Luxor Mini para grifería monocomando', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806128/Suplemento_Luxor_Mini_para_grifer%C3%ADa_monocomando_pza9lo.jpg' },
  { id: 332, name: 'Suplemento Luxor SI85 para grifería monocomando', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806130/Suplemento_Luxor_SI85_para_grifer%C3%ADa_monocomando_ocl8rw.jpg' },
  { id: 333, name: 'Suplemento Q84 para grifería monocomando', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806131/Suplemento_Q84_para_grifer%C3%ADa_monocomando_hvzvia.jpg' },
  { id: 334, name: 'Suplemento Q85 para grifería monocomando', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806133/Suplemento_Q85_para_grifer%C3%ADa_monocomando_nmnarg.jpg' },
  { id: 335, name: 'Suplemento Quadra Max para grifería monocomando', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806135/Suplemento_Quadra_Max_para_grifer%C3%ADa_monocomando_cj9d9r.jpg' },
  { id: 336, name: 'Suplemento X28 para grifería monocomando', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806136/Suplemento_X28_para_grifer%C3%ADa_monocomando_dep1rq.jpg' },
  { id: 337, name: 'Tabla compacto estructural Curve', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806137/Tabla_compacto_estructural_Curve_lsiyf7.jpg' },
  { id: 338, name: 'Tabla de madera O37', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806139/Tabla_de_madera_O37_hdrwju.jpg' },
  { id: 339, name: 'Tabla de madera Q37', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806141/Tabla_de_madera_Q37_xbv6zs.jpg' },
  { id: 340, name: 'Tabla de madera TA34', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806142/Tabla_de_madera_TA_34_v5zzgl.jpg' },
  { id: 341, name: 'Tabla de Montelli Q71', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806144/Tabla_de_Montelli_Q71_xgvr6w.jpg' },
  { id: 342, name: 'Tabla de vidrio templado Curve', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806145/Tabla_de_vidrio_templado_Curve_t6g27i.jpg' },
  { id: 343, name: 'Tabla de vidrio templado LQ', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806147/Tabla_de_vidrio_templado_LQ_jrfprt.jpg' },
  { id: 344, name: 'Tabla de vidrio templado Q55', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806148/Tabla_de_vidrio_templado_Q55_jfxoel.jpg' },
  { id: 345, name: 'Tabla Luxor Compact de Madera: TALC SI71', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806150/Tabla_Luxor_Compact_de_Madera_jh2dym.jpg' },
  { id: 346, name: 'Tabla Luxor de madera: TALU', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806151/Tabla_Luxor_de_madera_h4q7p2.jpg' },
  { id: 347, name: 'Tabla Luxor Mini de Madera: TALM', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806153/Tabla_Luxor_Mini_de_Madera_bzaara.jpg' },
  { id: 348, name: 'Tabla madera Q37', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806154/Tabla_madera_Q37_fvtghq.jpg' },
  { id: 349, name: 'Tabla madera Q40', category: 'Accesorios', image: 'https://res.cloudinary.com/dhm3hgkzo/image/upload/v1727806156/Tabla_madera_Q40_w38ask.jpg' },
]

export const categories: Category[] = ['Todos', 'Mármol', 'Granito', 'Neolith', 'Purastone', 'Silestone', 'Dekton', 'Bachas', 'Accesorios']